version: "3.3"

services:
  todoapp:
    image: node:12-alpine
    container_name: todoapp 
    restart: unless-stopped
    command: sh -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: "j2yiAE3wQUF8DWetExSgrCVei#"
      MYSQL_DB: todos
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.todoapp.rule=Host(`todoapp.localhost`)"
      - "traefik.http.routers.todoapp.tls=true"
      - "traefik.http.services.todoapp.loadbalancer.server.port=3000"
      - "traefik.http.routers.todoapp.middlewares=authelia@docker"
    networks:
      - proxy
      - default

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "j2yiAE3wQUF8DWetExSgrCVei#"
      MYSQL_DATABASE: todos
    networks:
      - default

  reverse-proxy:
    image: traefik:v2.9.4
    container_name: traefik
    restart: unless-stopped
    ports:
      # Web
      #- 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik_data/config/static.yml:/etc/traefik/traefik.yml:ro
      - ./traefik_data/config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik_data/certs:/etc/certs:ro
    networks:
      - proxy
      - default

  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: always
    volumes:
       - ./authelia/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia.rule=Host(`auth.todoapp.localhost`)"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.todoapp.localhost/"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
    networks:
      - proxy
      - default


networks:
  proxy:
    external: true
