users:
  user:
    displayname: "User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$ZSZoeae9wUImUd/icJeUXw$xRpXDm+RVLg3s3clDdGJWYX9/AxDgPRvDZt+x6UNM9E"
    email: user@mymail.com
    groups:
      - admins